---
version: "3"
services:
  go-upload:
    build: .
    restart: unless-stopped
    ports:
        - "8080:8080"
    environment:
        JWT_SECRET_KEY: "MyVeryHardPassw00Rd!"
        JWT_VALID_DAYS: 365
        PORT: 8080

